version: "3"

volumes:
  database:
    driver: local

services:
  postgres:
    platform: linux/amd64
    image: postgres:15
    container_name: hero_app_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: hero_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
